const ingredientesProhibidos = [
  "Embutido",
  "Chorizo ibérico",
  "Chorizo curado",
  "Chorizo cular",
  "Chorizo de León",
  "Chorizo riojano",
  "Chorizo de Pamplona",
  "Chorizo zamorano",
  "Chorizo de Cantimpalos",
  "Chorizo gallego",
  "Chistorra",
  "Salchichón ibérico",
  "Salchichón de Vic",
  "Salchichón casero",
  "Fuet",
  "Fuet de Vic",
  "Longaniza de Aragón",
  "Longaniza de Pascua",
  "Longaniza de Graus",
  "Longaniza fresca",
  "Butifarra blanca",
  "Butifarra negra",
  "Butifarra catalana",
  "Butifarra d'ou",
  "Butifarrón mallorquín",
  "Morcilla de Burgos",
  "Morcilla de arroz",
  "Morcilla de cebolla",
  "Morcilla asturiana",
  "Morcilla leonesa",
  "Morcilla de Extremadura",
  "Morcilla de calabaza",
  "Morcilla de verano",
  "Sobrasada mallorquina",
  "Sobrasada ibérica",
  "Sobrasada de Mallorca",
  "Lomo embuchado",
  "Lomo ibérico",
  "Lomo de orza",
  "Lomo adobado",
  "Caña de lomo",
  "Cabecero de lomo",
  "Coppa",
  "Cecina de León",
  "Cecina de vaca",
  "Cecina de cabra",
  "Jamón serrano",
  "Jamón ibérico",
  "Jamón de bellota",
  "Paleta ibérica",
  "Panceta curada",
  "Panceta adobada",
  "Tocino ibérico",
  "Cabeza de jabalí",
  "Chicharrones",
  "Chicharrón de Cádiz",
  "Chicharrón de cerdo",
  "Fiambre de cerdo",
  "Fiambre de pavo",
  "Mortadela",
  "Mortadela con aceitunas",
  "Mortadela italiana",
  "Salami",
  "Salami picante",
  "Salami ahumado",
  "Pepperoni español",
  "Jamón cocido",
  "Jamón dulce",
  "Lacón gallego",
  "Lacón curado",
  "Codillo cocido",
  "Pata de cerdo curada",
  "Pata cocida",
  "Manitas de cerdo curadas",
  "Oreja curada",
  "Lengua curada",
  "Lengua embuchada",
  "Lengua cocida",
  "Fiambre trufado",
  "Gallina trufada",
  "Rillette de cerdo",
  "Pâté de cerdo",
  "Pâté ibérico",
  "Pâté de campaña",
  "Paté de hígado",
  "Paté a la pimienta",
  "Salchicha blanca",
  "Salchicha roja",
  "Salchicha cocida",
  "Weisswurst (versión española)",
  "Salchichón de jabalí",
  "Chorizo de ciervo",
  "Morcón ibérico",
  "Morcón de chorizo",
  "Morcón de lomo",
  "Blanquet",
  "Fiambre de cabeza",
  "Fiambre de lengua",
  "Embutido de caza",
  "Sobrasada de caza",
  "Embutido vegano (imitación)",
  "Chorizo vegetal (imitación)",
  "Salchichas",
  "Hamburguesa preparada",
  "Pescado (preparado)",
  "Marisco (preparado)",
  "Palitos de cangrejo (preparado)",
  "Croquetas de bacalao (preparado)",
  "Croquetas de merluza (preparado)",
  "Croquetas de gambas (preparado)",
  "Albóndigas de pescado (preparado)",
  "Hamburguesa de atún (preparado)",
  "Hamburguesa de salmón (preparado)",
  "Hamburguesa de merluza (preparado)",
  "Varitas de merluza empanadas (preparado)",
  "Filetes de merluza rebozados (preparado)",
  "Filetes de bacalao rebozados (preparado)",
  "Lomos de salmón con eneldo (preparado)",
  "Salmón marinado (preparado)",
  "Salmón ahumado (preparado)",
  "Trucha ahumada (preparado)",
  "Anchoas en aceite (preparado)",
  "Boquerones en vinagre (preparado)",
  "Boquerones en aceite (preparado)",
  "Mejillones en escabeche (preparado)",
  "Mejillones al vapor en conserva (preparado)",
  "Calamares en su tinta (preparado)",
  "Calamares a la romana (preparado)",
  "Rabas empanadas (preparado)",
  "Pulpo cocido al vacío (preparado)",
  "Pulpo a la gallega (preparado)",
  "Pulpo con alioli (preparado)",
  "Gambas al ajillo congeladas (preparado)",
  "Langostinos cocidos envasados (preparado)",
  "Cola de langosta cocida (preparado)",
  "Buey de mar cocido (preparado)",
  "Nécora cocida (preparado)",
  "Zamburiñas en salsa vieira (preparado)",
  "Vieiras gratinadas congeladas (preparado)",
  "Almejas al ajillo congeladas (preparado)",
  "Chipirones rellenos en salsa (preparado)",
  "Chipirones encebollados (preparado)",
  "Sepia en su tinta (preparado)",
  "Cazuela de mariscos congelada (preparado)",
  "Paella de marisco (preparado)",
  "Arroz negro con calamares (preparado)",
  "Fideuá de marisco (preparado)",
  "Sopa de pescado (preparado)",
  "Crema de marisco (preparado)",
  "Consomé de pescado (preparado)",
  "Pimientos rellenos de bacalao (preparado)",
  "Pimientos del piquillo con atún (preparado)",
  "Tortillitas de camarones (preparado)",
  "Buñuelos de bacalao (preparado)",
  "Bacalao al pil-pil (preparado)",
  "Bacalao dorado (preparado)",
  "Merluza en salsa verde (preparado)",
  "Merluza a la gallega (preparado)",
  "Bacalao con tomate (preparado)",
  "Atún en escabeche (preparado)",
  "Bonito en aceite de oliva (preparado)",
  "Bonito en escabeche (preparado)",
  "Caballa en conserva (preparado)",
  "Sardinas en tomate (preparado)",
  "Sardinas en aceite de oliva (preparado)",
  "Tacos de atún (preparado)",
  "Tartar de salmón (preparado)",
  "Tartar de atún rojo (preparado)",
  "Ceviche de corvina (preparado)",
  "Ceviche de langostinos (preparado)",
  "Sashimi de salmón (preparado)",
  "Sushi variado (preparado)",
  "Nigiri de atún (preparado)",
  "Makis de salmón con aguacate (preparado)",
  "Temaki de cangrejo y pepino (preparado)",
  "Poke bowl de atún (preparado)",
  "Poke bowl de salmón (preparado)",
  "Lasaña de pescado (preparado)",
  "Cannelloni de marisco (preparado)",
  "Empanada de atún (preparado)",
  "Empanada de pulpo (preparado)",
  "Mini empanadillas de gambas (preparado)",
  "Nuggets de pescado (preparado)",
  "Tortitas de pescado (preparado)",
  "Rollitos de marisco (preparado)",
  "Timbal de marisco (preparado)",
  "Mousselina de pescado (preparado)",
  "Terrina de salmón (preparado)",
  "Ensaladilla rusa con atún (preparado)",
  "Ensalada de mariscos (preparado)",
  "Canelones de atún (preparado)",
  "Huevos rellenos de atún (preparado)",
  "Pastel de cabracho (preparado)",
  "Pastel de pescado (preparado)",
  "Bacalao gratinado (preparado)",
  "Rape al horno (preparado)",
  "Trucha a la navarra (preparado)",
  "Atún encebollado (preparado)",
  "Gambas con gabardina (preparado)",
  "Gambón al horno (preparado)",
  "Merluza a la romana (preparado)",
  "Pescado rebozado al limón (preparado)",
  "Langostinos empanados (preparado)",
  "Calamares rellenos (preparado)",
  "Brochetas de marisco (preparado)",
  "Empanadillas de bacalao y pasas (preparado)",
  "Productos loncheados con conservantes",
  "Alimentos cocinados con embutidos",
  "Alimentos con levaduras",
  "Patatas fritas hechas con freidora que se utilizan también para freir croquetas o empanadillas",
  "Salsas ligadas con harina",
  "Rebozados",
  "Purés",
  "Puré",
  "Rebozado",
  "Picatostes de pan de trigo",
  "Cerveza",
  "Whisky",
  "Evitar todos aquellos alimentos de los que no se tenga la certeza de que NO contienen leche o trazas de leche",
  "Leche de vaca natural",
  "Leche embotellada o en brick",
  "Leche en polvo",
  "Leche descremada",
  "Leche condensada",
  "Leche evaporada",
  "Leche para la lactancia",
  "Nata",
  "Yogur",
  "Natillas",
  "Flan",
  "Quesos",
  "Requesón",
  "Quesitos en porciones",
  "Natillas de chocolate",
  "Arroz con leche",
  "Mantequilla",
  "Helados",
  "Cuajada",
  "Batidos",
  "Productos elaborados con bechamel (croquetas)",
  "Productos elaborados con bechamel (lasaña)",
  "Productos que contienen leche en alguna cantidad (galletas)",
  "Productos que contienen leche en alguna cantidad (magdalenas)",
  "Productos que contienen leche en alguna cantidad (pasteles)",
  "Productos que contienen leche en alguna cantidad (repostería)",
  "Pastelitos (Donuts)",
  "Pastelitos (Bollycaos)",
  "Chocolates con leche",
  "Caramelos con leche (Sugus y similares)",
  "Ciertas margarinas (Tulipán, Vita)",
  "Cremas de cacao (Nocilla y similares)",
  "Jamón de York",
  "Embutidos (chorizo, salchichón, mortadela, sobrasada, longanizas, etc)",
  "Todos los productos realizados con leche de cabra y oveja",
  "Productos manufacturados que contengan leche",
  "Productos manufacturados que contengan caseina",
  "Productos manufacturados que contengan caseinato cálcico (E-4511)",
  "Productos manufacturados que contengan caseinato sódico (E-4512)",
  "Productos manufacturados que contengan caseinato potásico (E-4513)",
  "Hidrolisatos",
  "Lactoalbumina",
  "El término 'caldo deshidratado' puede implicar que el alimento contiene ciertas grasas de leche (nata, mantequilla) sin especificar",
  "El término 'grasas animales' puede implicar que el alimento contiene ciertas grasas de leche (nata, mantequilla) sin especificar",
  "El término 'cremas' puede implicar que el alimento contiene ciertas grasas de leche (nata, mantequilla) sin especificar",
  "La denominación 'proteínas' puede utilizar proteínas de leche sin especificar el contenido",
  "La denominación de 'aromas' pueden ser de queso o contener leche",
  "Cualquier producto que contenga como ingrediente trigo y/o derivados: almidón, harina, panes, pastas alimenticias, cerveza, etc",
  "Cualquier producto que contenga como ingrediente avena y/o derivados: almidón, harina, panes, pastas alimenticias, cerveza, etc",
  "Cualquier producto que contenga como ingrediente cebada y/o derivados: almidón, harina, panes, pastas alimenticias, cerveza, etc",
  "Cualquier producto que contenga como ingrediente centeno y/o derivados: almidón, harina, panes, pastas alimenticias, cerveza, etc",
  "Cualquier producto que contenga como ingrediente espelta y/o derivados: almidón, harina, panes, pastas alimenticias, cerveza, etc",
  "Cualquier producto que contenga como ingrediente kamut y/o derivados: almidón, harina, panes, pastas alimenticias, cerveza, etc",
  "Cualquier producto que contenga como ingrediente triticale y/o derivados: almidón, harina, panes, pastas alimenticias, cerveza, etc",
  "Como norma general, deben eliminarse de la dieta todos los productos a granel, los elaborados artesanalmente y los que no estén etiquetados, donde no se pueda comprobar el listado de ingredientes",
  "Productos que contienen o pueden contener gluten: gluten",
  "Productos que contienen o pueden contener gluten: cereales",
  "Productos que contienen o pueden contener gluten: harina",
  "Productos que contienen o pueden contener gluten: almidones modificados (E-1404, E-1410, E-1412, E-1413, E-1414, E-1420, E-1422, E-1440, E-1442, E-1450)",
  "Productos que contienen o pueden contener gluten: amiláceos",
  "Productos que contienen o pueden contener gluten: fécula",
  "Productos que contienen o pueden contener gluten: fibra",
  "Productos que contienen o pueden contener gluten: espesantes",
  "Productos que contienen o pueden contener gluten: sémola",
  "Productos que contienen o pueden contener gluten: proteína",
  "Productos que contienen o pueden contener gluten: proteína vegetal",
  "Productos que contienen o pueden contener gluten: hidrolizado de proteína",
  "Productos que contienen o pueden contener gluten: malta",
  "Productos que contienen o pueden contener gluten: extracto de malta",
  "Productos que contienen o pueden contener gluten: levadura",
  "Productos que contienen o pueden contener gluten: seitán",
  "Productos que contienen o pueden contener gluten: extracto de levadura",
  "Productos que contienen o pueden contener gluten: especias",
  "Productos que contienen o pueden contener gluten: aromas",
  "Bechamel",
  "Precocinados",
  "Cualquier tipo de salsa o sopa que se reconstituya con agua",
  "Salmorejo"
];

const ingredientesPermitidos = [
  "Frutas (excepto las que produzcan alergia oral)",
  "Pasta y fideos (para celíacos sin leche)",
  "Arroz con tomate",
  "Arroz ensalada",
  "Arroz con atún",
  "Paella",
  "Arroz con carne",
  "Arroz con verduras",
  "Maíz",
  "Quinoa con cualquier tipo de verduras",
  "Quinoa con tomate",
  "Carne fresca",
  "Carne a la plancha",
  "Pollo (filetes de pechuga de pollo)",
  "Pollo (alitas de pollo)",
  "Cerdo (filetes de lomo)",
  "Cerdo (solomillo)",
  "Cerdo (secreto/presa)",
  "Ternera (filetes de aguja)",
  "Ternera (entrecot)",
  "Ternera (solomillo)",
  "Pescado fresco al horno",
  "Pescado fresco a la plancha",
  "Lubina (pescado fresco y al horno/plancha)",
  "Besugo (pescado fresco y al horno/plancha)",
  "Trucha (pescado fresco y al horno/plancha)",
  "Dorada (pescado fresco y al horno/plancha)",
  "Atún (pescado fresco y al horno/plancha)",
  "Salmón (pescado fresco y al horno/plancha)",
  "Bonito o palometa con tomate (pescado fresco y al horno/plancha)",
  "Bacalao con arroz y patatas (pescado fresco y al horno/plancha)",
  "Sardinas (pescado fresco y al horno/plancha)",
  "Caballa (pescado fresco y al horno/plancha)",
  "Pulpo a la gallega (pescado fresco y al horno/plancha)",
  "Lentejas (cuando el plato contenga algún embutido de riesgo, debería ser evitado)",
  "Cocido (cuando el plato contenga algún embutido de riesgo, debería ser evitado)",
  "Guisante con jamón (cuando el plato contenga algún embutido de riesgo, debería ser evitado)",
  "Alubias o judías blancas (cuando el plato contenga algún embutido de riesgo, debería ser evitado)",
  "Huevo (si se consume fuera de casa, preguntar si se ha frito en aceite donde haya podido contaminarse con rebozados (huevo frito) y si es tortilla de patatas industrial (posibilidad de contener gluten)",
  "Patatas frescas",
  "Patatas cocinadas",
  "Patatas de bolsa",
  "Patatas fritas (asegurarse de que no se ha utilizado el aceite previamente para freír cualquier tipo de rebozado: Ej. croquetas, empanadillas, san jacobos)",
  "Verdura (preferiblemente frescas y no en salsas o encurtidas)",
  "Lechuga (preferiblemente frescas y no en salsas o encurtidas)",
  "Acelga (preferiblemente frescas y no en salsas o encurtidas)",
  "Tomate (preferiblemente frescas y no en salsas o encurtidas)",
  "Calabaza (preferiblemente frescas y no en salsas o encurtidas)",
  "Calabacín (preferiblemente frescas y no en salsas o encurtidas)",
  "Zanahoria (preferiblemente frescas y no en salsas o encurtidas)",
  "Pimiento (preferiblemente frescas y no en salsas o encurtidas)",
  "Ajo (preferiblemente frescas y no en salsas o encurtidas)",
  "Cebolla (preferiblemente frescas y no en salsas o encurtidas)",
  "Remolacha (preferiblemente frescas y no en salsas o encurtidas)",
  "Apio (preferiblemente frescas y no en salsas o encurtidas)",
  "Alcachofa (preferiblemente frescas y no en salsas o encurtidas)",
  "Brócoli (preferiblemente frescas y no en salsas o encurtidas)",
  "Coliflor (preferiblemente frescas y no en salsas o encurtidas)",
  "Berenjena (preferiblemente frescas y no en salsas o encurtidas)",
  "Espárragos (preferiblemente frescas y no en salsas o encurtidas)",
  "Aceite de oliva",
  "Bebidas gaseosas",
  "Aceitunas",
  "Boquerones en vinagre",
  "Biscottes para celíacos SIN leche",
  "Productos aptos para celíacos, SIEMPRE Y CUANDO NO CONTENGAN LECHE O PROTEÍNA DE VACA, realizados con harina de arroz, maíz, quinoa, soja o legumbres (soja, garbanzos, habas, altramuz, algarroba, guisantes",
  "Productos (bebidas, yogures, batidos) de soja",
  "Productos (bebidas, yogures, batidos) de maíz",
  "Productos (bebidas, yogures, batidos) de arroz",
  "Productos (bebidas, yogures, batidos) de avellanas",
  "Productos (bebidas, yogures, batidos) de almendras",
  "Productos (bebidas, yogures, batidos) de nueces",
  "Productos (bebidas, yogures, batidos) de quinoa",
  "Productos (bebidas, yogures, batidos) de amaranto",
  "Chocolate negro puro SIN leche",
  "Aconsejable que todos los productos realizados con harina de maíz o arroz tengan certificada la ausencia de gluten y leche en los ingredientes del etiquetado",
  "Puede contener trazas de... no implica que no sean productos seguros, aunque no se puede descartar una mínima contaminación accidental",
  "Café con leche de soja",
  "Té con leche de soja",
  "Bebidas de soja",
  "Yogures de soja",
  "Arroz",
  "Almendras",
  "Avellanas",
  "Nueces",
  "Quinoa",
  "Amaranto",
  "Bollería para celíacos (maíz, arroz) sin leche en su composición. Pueden contener huevo y soja",
  "Repostería para celíacos (maíz, arroz) sin leche en su composición. Pueden contener huevo y soja",
  "Tortitas para celíacos (maíz, arroz) sin leche en su composición. Pueden contener huevo y soja",
  "Vino",
  "Ginebra",
  "Vodka",
  "Ron de caña",
  "Café (sin leche)",
  "Té (sin leche)",
  "Tónica",
  "Mosto",
  "Zumos de frutas",
  "Frutas (si come fuera de casa)",
  "Ensaladas (si come fuera de casa)",
  "Pescados a la plancha (si come fuera de casa)",
  "Carnes a la plancha (si come fuera de casa)",
  "Almendra (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Avellana (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nuez (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pistacho (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Anacardo (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Piñón (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Cacahuete (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nuez de macadamia (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nuez pecana (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Castaña (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nuez de Brasil (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Chufa (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de girasol (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de calabaza (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de sésamo (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de lino (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de chía (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Almendra cruda (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Almendra tostada (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Almendra salada (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Almendra con piel (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Avellana cruda (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Avellana tostada (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pistacho crudo (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pistacho tostado (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pistacho salado (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Cacahuete tostado (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Cacahuete frito (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Cacahuete con miel (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Anacardo crudo (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Anacardo tostado (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Anacardo salado (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nuez común (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nuez negra (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nuez moscada (como especia, evitar contacto si hay antecedentes alérgicos)",
  "Castaña cocida (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Castaña asada (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Castaña pilonga (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Piñón nacional (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Piñón chino (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Macadamia cruda (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Macadamia tostada (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pecana cruda (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pecana tostada (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Sésamo blanco (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Sésamo negro (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semillas de cáñamo (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semillas de amapola (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semillas de mostaza (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semillas de albahaca (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de melón (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de sandía (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de uva (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Semilla de papaya (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Maní garrapiñado (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Turrón de almendra (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Manteca de almendra (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Crema de cacahuete (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Crema de avellana (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Tahini (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Harina de almendra (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Harina de castaña (evitando aquellos con los que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Manzana (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Plátano (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Naranja (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pera (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Mandarina (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Uva (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Sandía (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Melón (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Fresa (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Kiwi (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Piña (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Cereza (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Melocotón (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Nectarina (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Albaricoque (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Ciruela (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Mango (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Papaya (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Granada (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Higo (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Chirimoya (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Caqui (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Limón (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pomelo (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Frambuesa (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Mora (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Grosella (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Aguacate (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Lima (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Coco (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Tamarindo (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Guayaba (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Carambola (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Maracuyá (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Litchi (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Níspero (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Durian (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Feijoa (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Mangostán (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Rambután (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Physalis (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Acerola (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Arándano (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Melón cantalupo (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Melón galia (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pitahaya (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Zapote (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Mamey (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Camu camu (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Papayuela (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Longan (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Jaca (jackfruit) (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Pasa (uva seca) (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Dátil (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Higo seco (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Banana roja (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Cereza negra (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Plátano macho (evitando aquellas con las que se ha tenido síntomas alérgicos previamente, incluido picor o acorchamiento de la lengua o la garganta)",
  "Jamón serrano (de piezas enteras)",
  "Lomo (de piezas enteras)",
  "Huevo",
  "Merluza (NO preparado)",
  "Bacalao fresco (NO preparado)",
  "Salmón fresco (NO preparado)",
  "Atún rojo (NO preparado)",
  "Trucha (NO preparado)",
  "Rape (NO preparado)",
  "Caballa (NO preparado)",
  "Dorada (NO preparado)",
  "Lubina (NO preparado)",
  "Corvina (NO preparado)",
  "Bonito del norte (NO preparado)",
  "Jurel (NO preparado)",
  "Rodaballo (NO preparado)",
  "Lenguado (NO preparado)",
  "Gallo (NO preparado)",
  "Pez espada (NO preparado)",
  "Anchoas frescas (NO preparado)",
  "Boquerones frescos (NO preparado)",
  "Sardinas frescas (NO preparado)",
  "Anguila (NO preparado)",
  "Chicharro (NO preparado)",
  "Palometa (NO preparado)",
  "Pargo (NO preparado)",
  "Mero (NO preparado)",
  "Besugo (NO preparado)",
  "Tiburón cazón (NO preparado)",
  "Salmonete (NO preparado)",
  "Llampuga (NO preparado)",
  "Congrio (NO preparado)",
  "Pez de San Pedro (NO preparado)",
  "Gambas frescas (NO preparado)",
  "Langostinos frescos (NO preparado)",
  "Cigalas (NO preparado)",
  "Nécoras (NO preparado)",
  "Buey de mar vivo (NO preparado)",
  "Langosta (NO preparado)",
  "Almejas (NO preparado)",
  "Berberechos (NO preparado)",
  "Navajas (NO preparado)",
  "Coquinas (NO preparado)",
  "Mejillones vivos (NO preparado)",
  "Vieiras frescas (NO preparado)",
  "Zamburiñas (NO preparado)",
  "Ostras (NO preparado)",
  "Erizos de mar (NO preparado)",
  "Caracol de mar (NO preparado)",
  "Pulpo crudo (NO preparado)",
  "Sepia cruda (NO preparado)",
  "Calamar fresco (NO preparado)",
  "Chipirones frescos (NO preparado)",
  "Tinta de calamar (NO preparado)",
  "Huevas de pescado frescas (NO preparado)",
  "Huevas de merluza (NO preparado)",
  "Huevas de trucha (NO preparado)",
  "Huevas de salmón (NO preparado)",
  "Colas de rape (NO preparado)",
  "Filetes de lenguado (NO preparado)",
  "Filetes de bacalao sin curar (NO preparado)",
  "Lomos de salmón fresco (NO preparado)",
  "Tacos de atún fresco (NO preparado)",
  "Medallones de merluza (NO preparado)",
  "Rodajas de congrio (NO preparado)",
  "Pescadilla (NO preparado)",
  "Chanquetes (NO preparado)",
  "Cazón en crudo (NO preparado)",
  "Gallineta (NO preparado)",
  "Rabil (atún claro fresco) (NO preparado)",
  "Cabracho fresco (NO preparado)",
  "Marrajo (NO preparado)",
  "Melva fresca (NO preparado)",
  "Pez limón (NO preparado)",
  "Aguja (NO preparado)",
  "Tiburón azul (NO preparado)",
  "Pez mantequilla (NO preparado)",
  "Espadín (NO preparado)",
  "Sábalo (NO preparado)",
  "Trucha asalmonada (NO preparado)",
  "Lubina salvaje (NO preparado)",
  "Dorada salvaje (NO preparado)",
  "Lota (bacalao de agua dulce) (NO preparado)",
  "Pejerrey (NO preparado)",
  "Tilapia fresca (NO preparado)",
  "Panga fresca (NO preparado)",
  "Siluro (NO preparado)",
  "Pez gato (NO preparado)",
  "Esturión fresco (NO preparado)",
  "Albur (NO preparado)",
  "Tenca (NO preparado)",
  "Lenguadina (NO preparado)",
  "Raya (NO preparado)",
  "Chopa (NO preparado)",
  "Pez luna (NO preparado)",
  "Arenque fresco (NO preparado)",
  "Taimén (NO preparado)",
  "Bogavante (NO preparado)",
  "Pez globo (NO preparado)",
  "Trucha arcoíris (NO preparado)",
  "Engraulis (boquerón grande) (NO preparado)",
  "Merluza congelada natural (NO preparado)",
  "Salmón congelado sin aditivos (NO preparado)",
  "Cola de langosta cruda congelada (NO preparado)",
  "Gambón crudo congelado (NO preparado)",
  "Mejillón crudo congelado (NO preparado)",
  "Mariscos (no preparado)",
  "Pescado (no preparado)",
  "Hamburguesas caseras",
  "Verduras",
  "Lechuga",
  "Acelga",
  "Canónigos",
  "Rúcula",
  "Berros",
  "Endibia",
  "Col",
  "Col rizada",
  "Col lombarda",
  "Col de Bruselas",
  "Coliflor",
  "Romanesco",
  "Cebolla",
  "Cebolleta",
  "Ajo tierno",
  "Chalota",
  "Apio nabo",
  "Tomate",
  "Pimiento verde",
  "Pimiento rojo",
  "Pimiento amarillo",
  "Pimiento del padrón",
  "Berenjena",
  "Pepino",
  "Calabaza",
  "Maíz tierno",
  "Habas",
  "Champiñón",
  "Seta shiitake",
  "Enoki",
  "Portobello",
  "Patata",
  "Boniato",
  "Yuca",
  "Jengibre",
  "Apio",
  "Cardo",
  "Pak choi",
  "Mostaza verde",
  "Alga wakame",
  "Acedera",
  "Malva",
  "Bledo",
  "Perejil",
  "Cilantro",
  "Cebollino",
  "Albahaca",
  "Hierbabuena",
  "Estragón",
  "Eneldo",
  "Laurel",
  "Romero",
  "Tomillo",
  "Salvia",
  "Oregano",
  "Lovage",
  "Cúrcuma fresca",
  "Habas baby",
  "Grelo",
  "Rape de tierra",
  "Salsifí",
  "Tupinambo",
  "Judión",
  "Pepinillo",
  "Repollo rizado",
  "Calabacín",
  "Chayote",
  "Okra",
  "Judía verde",
  "Guisante",
  "Tirabeque",
  "Alcachofa",
  "Espárrago verde",
  "Espárrago blanco",
  "Hinojo",
  "Puerro",
  "Ajo",
  "Ajo negro",
  "Rábano",
  "Rabanito",
  "Remolacha",
  "Zanahoria",
  "Nabo",
  "Nabicol",
  "Cúrcuma",
  "Espinaca",
  "Espinaca baby",
  "Escarola",
  "Brócoli",
  "Cima di rapa",
  "Mostaza roja",
  "Mizuna",
  "Brotes de soja",
  "Brotes de alfalfa",
  "Brotes de bambú",
  "Flor de calabaza",
  "Setas",
  "Shiitake",
  "Níscalo",
  "Verdolaga",
  "Ortiga",
  "Diente de león",
  "Escorzonera",
  "Kohlrabi",
  "Repollo",
  "Romanilla",
  "Tomatillo",
  "Chilaca",
  "Guindilla",
  "Cilantro (hoja)",
  "Perejil (hoja)",
  "Eneldo (hoja)",
  "Hojas de remolacha",
  "Hojas de zanahoria",
  "Romero (tierno)",
  "Lenteja pardina",
  "Lenteja castellana",
  "Lenteja roja",
  "Lenteja verde",
  "Lenteja beluga",
  "Garbanzos",
  "Garbanzo pedrosillano",
  "Garbanzo lechoso",
  "Garbanzos negros",
  "Alubia blanca",
  "Alubia pinta",
  "Alubia roja",
  "Alubia negra",
  "Alubia canela",
  "Alubia tolosana",
  "Alubia carilla",
  "Alubia fabada",
  "Judión de La Granja",
  "Frijol negro",
  "Frijol rojo",
  "Frijol mungo (mungo bean)",
  "Frijol azuki",
  "Soja",
  "Soja verde",
  "Soja negra",
  "Haba seca",
  "Haba verde",
  "Guisante seco",
  "Guisante verde",
  "Guisante partido",
  "Tirabeque (vaina comestible)",
  "Lentejón",
  "Lupino (altramuces)",
  "Altramuz dulce",
  "Cacahuete",
  "Edamame",
  "Soja texturizada",
  "Soja fermentada (tempeh)",
  "Tofu (derivado de soja)",
  "Yuba (piel de tofu)",
  "Garbanzos verdes (tiernos)",
  "Lenteja dupuy",
  "Lenteja egipcia",
  "Lenteja francesa",
  "Guandú (gandul)",
  "Guisante lágrima",
  "Haba de Lima",
  "Haba morada",
  "Alubia arrocina",
  "Alubia riñón",
  "Frijol bayo",
  "Frijol mayocoba",
  "Frijol flor de junio",
  "Frijol peruano",
  "Alubia planchada",
  "Alubia de riñón blanco",
  "Alubia vaquita",
  "Lenteja amarilla",
  "Soja germinada",
  "Lenteja negra",
  "Guisante morado",
  "Garbanzos verdes frescos",
  "Haba pelada",
  "Frijol ojo negro",
  "Frijol fava",
  "Frijol rosa",
  "Alubia morada",
  "Frijol zarco",
  "Frijol de árbol",
  "Lenteja india",
  "Guisante amarillo",
  "Guisante dulce",
  "Guisante silvestre",
  "Haba escarlata",
  "Frijol canario",
  "Frijol blanco grande",
  "Lenteja canadiense",
  "Lenteja turca",
  "Alubia blanca extra",
  "Alubia pinta extra",
  "Lenteja ecológica",
  "Garbanzos ecológicos",
  "Frijol blanco moteado",
  "Haba gruesa",
  "Haba de invierno",
  "Frijol criollo",
  "Soja blanca",
  "Lupino amargo",
  "Guisante negro",
  "Lenteja chana dal",
  "Toor dal",
  "Urad dal",
  "Moong dal",
  "Moth bean",
  "Rajma (frijol rojo indio)",
  "Kala chana (garbanzo negro)",
  "Chickling vetch (almorta)",
  "Vigna subterranea",
  "Psophocarpus",
  "Cicerbita",
  "Lablab",
  "Carnes",
  "Carnes de todo tipo"
];